---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb-system
  namespace: metallb-system
spec:
  interval: 24h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb-system
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb-system
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: metallb-system
        namespace: metallb-system
      interval: 12h
  install:
    remediation:
      retries: 3