---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-kubernetes
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/jrn90/homelab
  ignore: |
    /*

    !/kubernetes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/main/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
